import { createClient } from "@supabase/supabase-js";

const NEXT_PUBLIC_SUPABASE_URL = 'https://lghomslmpoioiixhxobb.supabase.co'
const NEXT_PUBLIC_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaG9tc2xtcG9pb2lpeGh4b2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkzMzIyNzcsImV4cCI6MjA0NDkwODI3N30.C1FmCCiPwZyzGy9gF_3nGAGGqa7WfBxa3VRQfCbnKk4'

export const supabase = createClient(NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY)
