import { Facebook, Twitter, Instagram, Linkedin, Github } from "lucide-react"
import { Link } from "react-router-dom"
import { Dialog, DialogContent, DialogTrigger } from "../ui/dialog"


export const data = [
    {
        name: "Privacy Policy",
        title: "Privacy Policy",
        p1: `PixelBrew AI values your privacy and is committed to protecting your personal information. This Privacy Policy outlines how we collect, use, store, and protect the information you provide when using our services`,
        p2: "",
        bulletPoints: [
            ` Information We Collect- Training Images: To personalize and improve your experience, we may collect and store images that you upload to train our AI model.
Prompts and Response Images: We collect the prompts you enter and the images generated in response to provide and enhance our Service.
Email Address: We may collect your email address for account management, communication, and support purposes. However, we do not share your email with any third-party entities unless required by law. `,
            `Information We Do Not Collect
Passwords: We do not collect or store any passwords associated with your account. We may rely on third-party authentication services, where applicable, to securely manage login credentials.`,
            `Access: You have the right to access the information we hold about you and request corrections if necessary.`
        ]
    },
    {
        name: "Terms of Service",
        title: "Terms and Conditions",
        p1: "",
        p2: "",
        bulletPoints: [
            "Acceptance of Terms- By using the services provided by PixelBrew AI, you agree to comply with and be bound by the following Terms and Conditions . If you do not agree to these Terms, you may not access or use our Service.",
            `Nature of AI-Generated Content- PixelBrew AI uses a cutting-edge text-to-image generation model to create unique images based on user input. Due to the limitations of current AI technology, images generated by PixelBrew AI may occasionally be inaccurate, contain unintended elements, or appear "hallucinated".`,
            ` Permissible Use of Content- Users are permitted to use images generated by PixelBrew AI for any purpose, including but not limited to personal, commercial, and promotional uses.`,
            `Prohibited Use and Account Termination- PixelBrew AI is not responsible for any misuse of the AI-generated content, including but not limited to uses that violate copyright, intellectual property laws, or involve harmful or malicious activities.`,
            `Contact Us- If you have any questions or concerns regarding these Terms and Conditions, please reach out to us at 100xdevspiyush@gmail.com`,
        ]
    },
    {
        name: "Refund Policy",
        title: "Refund Policy",
        p1: `At PixelBrew AI, we strive to provide a high-quality experience with our AI-generated image services. Due to the nature of digital products, we currently do not offer refunds once tokens are purchased`,
        p2: `However, if you experience any issues with payment or believe there has been a discrepancy, please don't hesitate to contact us at 100xdevspiyush@gmail.com. `,
        bulletPoints: [
            "Our team is here to help address any concerns and ensure a smooth experience with our platform.",
        ]
    },
]

export default function Footer() {
    return (
        <footer className="bg-black text-white py-12 font-sans border-t border-purple-700 border-opacity-40">
            <div className="container mx-auto px-4">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                    <div className="md:col-span-2">
                        <h2 className="text-2xl font-bold text-purple-400">PixelBrew AI</h2>
                        <p className="mt-2 text-gray-300 tracking-tight">Pixel perfect thumbnails, brewed by AI</p>
                        <div className="mt-4 flex space-x-4">
                            <Link to="https://x.com/piyushsainii" className="text-gray-400 hover:text-purple-400">
                                <Twitter className="h-6 w-6" />
                                <span className="sr-only">Twitter</span>
                            </Link>
                            <Link to="https://www.linkedin.com/in/piyush-saini-b860ab1bb/" className="text-gray-400 hover:text-purple-400">
                                <Linkedin className="h-6 w-6" />
                                <span className="sr-only">LinkedIn</span>
                            </Link>
                            <Link to="https://github.com/piyushhsainii" className="text-gray-400 hover:text-purple-400">
                                <Github className="h-6 w-6" />
                                <span className="sr-only">GitHub</span>
                            </Link>
                        </div>
                    </div>
                    <div>
                        <h3 className="text-lg font-semibold text-purple-400 mb-4">Product</h3>
                        <ul className="space-y-2">
                            <li><Link to="#howitworks" className="text-gray-300 hover:text-purple-400">Features</Link></li>
                            <li><Link to="shop" className="text-gray-300 hover:text-purple-400">Pricing</Link></li>
                            <li><Link to="explore" className="text-gray-300 hover:text-purple-400">Gallery</Link></li>
                        </ul>
                    </div>
                    <div>
                        <h3 className="text-lg font-semibold text-purple-400 mb-4">Company</h3>
                        <ul className="space-y-2">
                            <li><Link to="about-us" className="text-gray-300 hover:text-purple-400">About Us</Link></li>
                            <li><Link to="#" className="text-gray-300 hover:text-purple-400">Careers</Link></li>
                            <li><Link to="#" className="text-gray-300 hover:text-purple-400">Contact</Link></li>
                        </ul>
                    </div>
                </div>
                <div className="mt-8 pt-8 border-t border-gray-800">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
                        <div className="text-sm text-gray-400">
                            © {new Date().getFullYear()} PixelBrew AI. All rights reserved.
                        </div>
                    </div>
                    <div className="mt-4 text-sm text-gray-400">
                        {
                            data.map((data) => (
                                <>
                                    <Dialog>
                                        <DialogTrigger>
                                            <div className="hover:text-purple-400">{data.name}</div>
                                        </DialogTrigger>
                                        <DialogContent className="bg-black  w-[75vw] h-[90vh] md:min-h-[70vh] md:max-h-[80vh] mt-5  border border-purple-700 border-opacity-50 text-white font-sans" >
                                            <div className="overflow-y-scroll flex flex-col justify-between">
                                                <div className="text-2xl pb-4 md:pb-0" >
                                                    {data.title}
                                                </div>
                                                <div>{data.p1}</div>
                                                <div> {data.p2} </div>
                                                <div>
                                                    <ul>
                                                        {data.bulletPoints.map((list) => (
                                                            <li className="list-disc py-1 mx-4">{list} </li>
                                                        ))}
                                                    </ul>
                                                </div>
                                                <div className="text-lh text-right">
                                                    Thank you,
                                                    <div className="text-lh text-right">
                                                        Pixel Brew AI
                                                    </div>
                                                </div>
                                            </div>
                                        </DialogContent>

                                    </Dialog>
                                    {' | '}
                                </>
                            ))
                        }

                    </div>
                </div>
            </div>
        </footer>
    )
}