import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "../components/ui/accordion"


const FAQ = () => {


    const FAQ = [
        {
            question: "What is PixelBrew AI, and how does it work?",
            answer: ""
        },
        {
            question: "What types of images can I generate with PixelBrew AI?",
            answer: ""
        },
        {
            question: "How does the custom model training feature in PixelBrew AI V2 work?",
            answer: ""
        },
        {
            question: "Are the images generated by PixelBrew AI suitable for commercial use?",
            answer: ""
        },
        {
            question: "What should I do if I encounter issues with payment or generated images?",
            answer: ""
        },
    ]

    return (
        <div className="font-sans bg-black text-white py-7">
            <div className=" text-center font-sans text-2xl"> GENERAL FAQ </div>
            <div className="w-[90%] m-auto">
                <Accordion type="single" collapsible>
                    {
                        FAQ.map((data, index) => (
                            <AccordionItem value={`item-${index}`} className="border-purple-600">
                                <AccordionTrigger className="font-normal">{data.question}</AccordionTrigger>
                                <AccordionContent >
                                    <div>
                                        {data.answer}
                                    </div>
                                </AccordionContent>
                            </AccordionItem>
                        ))
                    }

                </Accordion>

            </div>
        </div>
    )
}

export default FAQ